name: Continuous Deployment Frontend(Prod)
on:
  push:
    branches: [ deploy ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: sujiththirumalaisamy/qanda-frontend:${{ github.sha }}

      - name: Clone staging-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/sujiththirumalaisamy/solana-ai-agent-ops.git
          cd solana-ai-agent-ops
          sed -i 's|image: sujiththirumalaisamy/qanda-frontend:.*|image: sujiththirumalaisamy/qanda-frontend:${{ github.sha }}|' frontend.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add frontend.yml
          git commit -m "Update frontend image to ${{ github.sha }}"
          git push https://${PAT}@github.com/sujiththirumalaisamy/solana-ai-agent-ops.git main
